handlers:
- name: restart chrony
  service: name=chrony state=restarted
  become: yes
  listen: "restart chrony"
- name: client
  apt: pkg=python-openstackclient state=present
  become: yes
  listen: "client"
- name: Changing config of mysql
  template:
   src: mysql_openstack.conf.j2
   dest: /etc/mysql/conf.d/openstack.cnf
  become: yes
  listen: 'Changing config of mysql'
  
